In [1]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(42)
# Create random tensor
random_tensor = tf.random.normal([4, 6])
print(random_tensor)
# Find rank and shape
print(tf.rank(random_tensor).numpy())
print(random_tensor.shape)
# Reshape and transpose
reshaped_tensor = tf.reshape(random_tensor, [2, 3, 4])
print(reshaped_tensor)
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])
print(transposed_tensor)
# Broadcasting
small_tensor = tf.constant([[1.0, 2.0, 3.0, 4.0]])
print(small_tensor)
broadcasted_result = small_tensor + random_tensor[:, :4]
print(broadcasted_result)


tf.Tensor(
[[ 0.3274685  -0.8426258   0.3194337  -1.4075519  -2.3880599  -1.0392479 ]
 [-0.5573232   0.539707    1.6994323   0.28893656 -1.5066116  -0.26454744]
 [-0.59722406 -1.9171132  -0.62044144  0.8504023  -0.40604794 -3.0258412 ]
 [ 0.9058464   0.29855987 -0.22561555 -0.7616443  -1.891714   -0.9384712 ]], shape=(4, 6), dtype=float32)
2
(4, 6)
tf.Tensor(
[[[ 0.3274685  -0.8426258   0.3194337  -1.4075519 ]
  [-2.3880599  -1.0392479  -0.5573232   0.539707  ]
  [ 1.6994323   0.28893656 -1.5066116  -0.26454744]]

 [[-0.59722406 -1.9171132  -0.62044144  0.8504023 ]
  [-0.40604794 -3.0258412   0.9058464   0.29855987]
  [-0.22561555 -0.7616443  -1.891714   -0.9384712 ]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[ 0.3274685  -0.8426258   0.3194337  -1.4075519 ]
  [-0.59722406 -1.9171132  -0.62044144  0.8504023 ]]

 [[-2.3880599  -1.0392479  -0.5573232   0.539707  ]
  [-0.40604794 -3.0258412   0.9058464   0.29855987]]

 [[ 1.6994323   0.28893656 -1.5066116  -0.26454744]
  [-0.22561555

In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
# Load iris dataset
iris = load_iris()
X = iris.data
y = iris.target
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Define model architecture
model = Sequential([
    Dense(64, activation='relu', input_shape=(4,)),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')
])
# Compile model with different loss functions
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# Train model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 173ms/step - accuracy: 0.6571 - loss: 0.9879 - val_accuracy: 0.7333 - val_loss: 0.8977
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7596 - loss: 0.8922 - val_accuracy: 0.8333 - val_loss: 0.8305
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8442 - loss: 0.8267 - val_accuracy: 0.8667 - val_loss: 0.7665
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8442 - loss: 0.7694 - val_accuracy: 0.8667 - val_loss: 0.7183
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8612 - loss: 0.7219 - val_accuracy: 0.9000 - val_loss: 0.6768
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9029 - loss: 0.6773 - val_accuracy: 0.9000 - val_loss: 0.6371
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9056 - loss: 0.6370 - val_accuracy: 0.9000 - val_loss: 0.5977
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8760 - loss: 0.6004 - val_accuracy: 0.8667 - val_loss: 0.5613

In [4]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten # Import Flatten
from tensorflow.keras.datasets import mnist
# Load MNIST dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()
# Normalize pixel values
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0
# Flatten the images
X_train = X_train.reshape(-1, 784) # Reshape X_train
X_test = X_test.reshape(-1, 784) # Reshape X_test
# Define model architecture
model = Sequential([
    Dense(64, activation='relu', input_shape=(784,)),
    Dense(32, activation='relu'),
    Dense(10, activation='softmax')
])
# Compile model with different optimizers
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# Train model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8537 - loss: 0.5052 - val_accuracy: 0.9524 - val_loss: 0.1540
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9565 - loss: 0.1474 - val_accuracy: 0.9607 - val_loss: 0.1244
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - accuracy: 0.9689 - loss: 0.1042 - val_accuracy: 0.9662 - val_loss: 0.1120
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9760 - loss: 0.0791 - val_accuracy: 0.9694 - val_loss: 0.1043
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9810 - loss: 0.0625 - val_accuracy: 0.9692 - val_loss: 0.1017
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9851 - loss: 0.0504 - val_accuracy: 0.9707 - val_loss: 0.0989
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9871 - loss: 0.0411 - val_accuracy: 0.9725 - val_loss: 0.1030
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9899 - loss: 0.0333

In [5]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import TensorBoard
# Define model architecture
model = Sequential([
    Dense(64, activation='relu', input_shape=(784,)),
    Dense(32, activation='relu'),
    Dense(10, activation='softmax')
])
# Compile model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# Define TensorBoard callback
tensorboard_callback = TensorBoard(log_dir='./logs', histogram_freq=1)
# Train model with TensorBoard logging
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test), callbacks=[tensorboard_callback])


Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - accuracy: 0.8507 - loss: 0.5083 - val_accuracy: 0.9550 - val_loss: 0.1526
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9599 - loss: 0.1378 - val_accuracy: 0.9640 - val_loss: 0.1172
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9714 - loss: 0.0951 - val_accuracy: 0.9690 - val_loss: 0.1043
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9782 - loss: 0.0736 - val_accuracy: 0.9720 - val_loss: 0.0942
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9819 - loss: 0.0595 - val_accuracy: 0.9739 - val_loss: 0.0876
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9856 - loss: 0.0486 - val_accuracy: 0.9748 - val_loss: 0.0875
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9876 - loss: 0.0409 - val_accuracy: 0.9733 - val_loss: 0.0930
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9903 - loss: 0.0333 